### ISSUE TITLE
minute.steps bug

### ISSUE THREAD

**Issue by altamont** [burgerga/shinyTime#11]
Hi,

Attached is a screenshot from when I run shinyTimeExample():
![shinyTimeExample_bug](https://user-images.githubusercontent.com/9896549/71113938-ac722d00-219c-11ea-8db2-939f31ec30e8.PNG)

You can see that the starting time for the second time input is incorrect.  This is related to the minute.steps parameter.  When I do not specify this parameter, the input is loaded with the correct value.  Looking at your code, I believe the issue lies with the roundTime function.

Thanks for making this package, I enjoy using it.

**Comment by burgerga** [comment]
Sorry for the (very) late reply, my notification settings were all wrong and I didn't get notifications for new issues.

This looks indeed like I need to write some new tests for the roundTime function, thanks for pointing it out!
