### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by burgerga** [burgerga/shinyTime#22]
Hi @nick-youngblut, I just noticed that the code is GPL-licensed (https://www.tldrlegal.com/license/gnu-general-public-license-v3-gpl-3). I want to change this to MIT (https://www.tldrlegal.com/license/mit-license) which is a bit more permissive, especially for commercial use. Do you agree (since your code was contributed under the GPL license)?

**Authors**
- [x] Gerhard
- [x] Nick Youngblut

**Comment by nick-youngblut** [comment]
Sorry @burgerga for the slow reply. I've been traveling.

> Do you agree (since your code was contributed under the GPL license)?

Yes, I agree! 👍
